# Generated by Django 3.2.12 on 2023-03-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signloginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='MALE', max_length=100),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='email',
            field=models.EmailField(default='', max_length=255, null=True),
        ),
    ]
